### ISSUE TITLE
[Compiler2022] Warning by TA

### ISSUE THREAD

**Issue by aben20807** [arasHi87/NCKU_HOMEWORK#3]
Hi @arasHi87 

Your code can be accessed in public. If anyone plagiarize your code, you will also have score penalty for this public repo. Please set this repo into private repo ASAP, and you can set it back to public after the semester. Thank you for the cooperation.

**Comment by arasHi87** [comment]
Oops, got it, I will deal with it later, thx for ur advice.

**Comment by arasHi87** [comment]
Curious to ask, how could u find mine repo (((ﾟдﾟ)))

**Comment by aben20807** [comment]
@arasHi87 

Still accessible.
